package IHM;

import Utility.BibalExceptions;
import Utility.DBConnection;
import dao.ReservationControl;
import dao.UsagerControl;

import static Utility.Utility.closeStatementResultSet;
import static Utility.Utility.initialiseRequetePreparee;
import static Utility.Utility.showMessageSucces;

import domaine.Usager;

import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import static java.lang.Integer.parseInt;
import java.awt.Color;
import java.awt.Font;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
/**
 * 
 * @author Diallo & Janati
 */
public class GestionReservations extends javax.swing.JDialog {

    public GestionReservations(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIdentifiant();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/bibliotheque_icone.png")));
    }

    /**
     * @wbp.parser.constructor
     */
    public GestionReservations(java.awt.Frame parent, boolean modal, String titre) {
        this(parent, modal);
        this.titre = titre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setForeground(new Color(255, 255, 0));
        titleLabel = new javax.swing.JLabel();
        panAjoutBas = new javax.swing.JPanel();
        nomLabel = new javax.swing.JLabel();
        identifiantLabel = new javax.swing.JLabel();
        identifiantUsagerCombo = new javax.swing.JComboBox();
        validerBouton = new javax.swing.JButton();
        validerBouton.setBackground(new Color(255, 255, 0));
        annulerBouton = new javax.swing.JButton();
        annulerBouton.setBackground(new Color(255, 255, 0));
        nomUsagerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Réserver");

        jPanel1.setBackground(new Color(255, 255, 0));
        jPanel1.setName("Gestion personnel"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1162, 608));
        jPanel1.setRequestFocusEnabled(false);

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titleLabel.setForeground(new Color(0, 0, 0));
        titleLabel.setText("Choisir Usager");

        panAjoutBas.setBackground(new Color(128, 128, 128));
        panAjoutBas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        nomLabel.setFont(new java.awt.Font("Arial", Font.BOLD, 18)); // NOI18N
        nomLabel.setForeground(new Color(255, 255, 255));
        nomLabel.setText("Nom usager");

        identifiantLabel.setFont(new java.awt.Font("Arial", Font.BOLD, 18)); // NOI18N
        identifiantLabel.setForeground(new Color(255, 255, 255));
        identifiantLabel.setText("Identifiant ");

        identifiantUsagerCombo.setFont(new java.awt.Font("Arial", Font.BOLD, 18)); // NOI18N
        identifiantUsagerCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choisir identifiant" }));
        identifiantUsagerCombo.setPreferredSize(new java.awt.Dimension(123, 26));
        identifiantUsagerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identifiantUsagerComboActionPerformed(evt);
            }
        });

        validerBouton.setFont(new java.awt.Font("Arial", Font.BOLD, 18)); // NOI18N
        validerBouton.setText("Valider");
        validerBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserver(evt);
            }
        });

        annulerBouton.setFont(new java.awt.Font("Arial", Font.BOLD, 18)); // NOI18N
        annulerBouton.setText("Annuler");
        annulerBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerBoutonActionPerformed(evt);
            }
        });

        nomUsagerLabel.setFont(new java.awt.Font("Arial", Font.BOLD, 18)); // NOI18N
        nomUsagerLabel.setText(" ");

        javax.swing.GroupLayout panAjoutBasLayout = new javax.swing.GroupLayout(panAjoutBas);
        panAjoutBasLayout.setHorizontalGroup(
        	panAjoutBasLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panAjoutBasLayout.createSequentialGroup()
        			.addGroup(panAjoutBasLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(Alignment.LEADING, panAjoutBasLayout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(panAjoutBasLayout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(nomLabel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(identifiantLabel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addGap(62)
        					.addGroup(panAjoutBasLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(identifiantUsagerCombo, 0, 230, Short.MAX_VALUE)
        						.addComponent(nomUsagerLabel, GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
        				.addGroup(Alignment.LEADING, panAjoutBasLayout.createSequentialGroup()
        					.addGap(54)
        					.addComponent(annulerBouton)
        					.addGap(80)
        					.addComponent(validerBouton)))
        			.addContainerGap())
        );
        panAjoutBasLayout.setVerticalGroup(
        	panAjoutBasLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panAjoutBasLayout.createSequentialGroup()
        			.addGap(28)
        			.addGroup(panAjoutBasLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(identifiantLabel)
        				.addComponent(identifiantUsagerCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(35)
        			.addGroup(panAjoutBasLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(nomLabel)
        				.addComponent(nomUsagerLabel))
        			.addPreferredGap(ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
        			.addGroup(panAjoutBasLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(annulerBouton)
        				.addComponent(validerBouton))
        			.addContainerGap())
        );
        panAjoutBas.setLayout(panAjoutBasLayout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panAjoutBas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(panAjoutBas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void identifiantUsagerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identifiantUsagerComboActionPerformed
        try {
            int usagerId = getUsagerID();
            if (usagerId != -1) {
                Usager usager = UsagerControl.findById(usagerId);
                if (null != usager) {
                    String nom = usager.getNom() + " " + usager.getPrenom();
                    nomUsagerLabel.setText(nom);
                }
            }
        } catch (BibalExceptions ex) {
            System.out.println("IHM.Emprunter.identifiantUsagerComboActionPerformed()");
        }
    }//GEN-LAST:event_identifiantUsagerComboActionPerformed

    private void reserver(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserver

        try {
            int usagerId = getUsagerID();
            if (usagerId != -1) {
                ReservationControl.reserver(usagerId, titre);
                showMessageSucces("Réservation enregistrée");
            } else {
                showMessageSucces("Veuillez choisir un identifiant");
            }
        } catch (BibalExceptions ex) {
            System.out.println("IHM.Reserver.validerBoutonActionPerformed()" + ex.getMessage());
        }
    }//GEN-LAST:event_reserver

    private int getUsagerID() {
        String id = identifiantUsagerCombo.getSelectedItem().toString();
        if (!id.equals("Choisir identifiant")) {
            return parseInt(id);
        }
        return -1;
    }

    private void setIdentifiant() {
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        try {
            final String SQL_SELECT_ID = "SELECT id FROM usager ";
            preparedStatement = initialiseRequetePreparee(DBConnection.getConnection(),
                    SQL_SELECT_ID, new Object[0]);
            resultSet = preparedStatement.executeQuery();
            int identifiant;
            while (resultSet.next()) {
                identifiant = resultSet.getInt("id");
                identifiantUsagerCombo.addItem(Integer.toString(identifiant));
            }
        } catch (SQLException | BibalExceptions e) {
            JOptionPane.showMessageDialog(null, "Erreurs d'accès à la base de données",
                    "Erreurs", JOptionPane.ERROR_MESSAGE);
        } finally {
            closeStatementResultSet(preparedStatement, resultSet);
        }
    }
    private void annulerBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerBoutonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerBoutonActionPerformed

    private String titre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerBouton;
    private javax.swing.JLabel identifiantLabel;
    private javax.swing.JComboBox identifiantUsagerCombo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JLabel nomUsagerLabel;
    private javax.swing.JPanel panAjoutBas;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton validerBouton;
    // End of variables declaration//GEN-END:variables
}
